# Base image
FROM node:latest-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose the port your application runs on
EXPOSE 3000

# Set environment variables
ENV NODE_ENV=production
ENV MONGODB_URI=mongodb://mongodb_host:27017/db_name

# Build the application
RUN npm run build

# Start the application
CMD ["npm", "start"]
